from .retriever_prompts import (
    RETRIEVER_SYSTEM_PROMPT,
    RETRIEVER_USER_PROMPT,
    RERANKING_PROMPT
)

from .reasoner_prompts import (
    REASONER_SYSTEM_PROMPT,
    REASONER_USER_PROMPT,
    VERIFICATION_PROMPT
)

from .explainer_prompts import (
    EXPLAINER_SYSTEM_PROMPT,
    EXPLAINER_USER_PROMPT,
    SIMPLIFICATION_PROMPT,
    FOLLOW_UP_QUESTIONS_PROMPT
)

__all__ = [
    # Retriever
    "RETRIEVER_SYSTEM_PROMPT",
    "RETRIEVER_USER_PROMPT",
    "RERANKING_PROMPT",

    # Reasoner
    "REASONER_SYSTEM_PROMPT",
    "REASONER_USER_PROMPT",
    "VERIFICATION_PROMPT",

    # Explainer
    "EXPLAINER_SYSTEM_PROMPT",
    "EXPLAINER_USER_PROMPT",
    "SIMPLIFICATION_PROMPT",
    "FOLLOW_UP_QUESTIONS_PROMPT",
]
